//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lib2122.DbConnection
{
    using System;
    using System.Collections.Generic;
    
    public partial class HistoryReaderTicket
    {
        public int Id { get; set; }
        public Nullable<int> IdBook { get; set; }
        public Nullable<int> IdReaderTicket { get; set; }
        public Nullable<System.DateTime> DateStart { get; set; }
        public Nullable<System.DateTime> DateEnd { get; set; }
        public Nullable<int> IdEmployee { get; set; }
        public string Comment { get; set; }
    
        public virtual Book Book { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual ReaderTicket ReaderTicket { get; set; }
    }
}
