//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lib2122.DbConnection
{
    using System;
    using System.Collections.Generic;
    
    public partial class Janr
    {
        public Janr()
        {
            this.Book = new HashSet<Book>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<Book> Book { get; set; }
    }
}
