//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lib2122.DbConnection
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class libraryKIUEntities : DbContext
    {
        public libraryKIUEntities()
            : base("name=libraryKIUEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Author> Author { get; set; }
        public DbSet<Book> Book { get; set; }
        public DbSet<Employee> Employee { get; set; }
        public DbSet<Gender> Gender { get; set; }
        public DbSet<HistoryReaderTicket> HistoryReaderTicket { get; set; }
        public DbSet<Janr> Janr { get; set; }
        public DbSet<Post> Post { get; set; }
        public DbSet<Reader> Reader { get; set; }
        public DbSet<ReaderTicket> ReaderTicket { get; set; }
        public DbSet<Shelf> Shelf { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
