//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lib2122.DbConnection
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reader
    {
        public Reader()
        {
            this.ReaderTicket = new HashSet<ReaderTicket>();
        }
    
        public int Id { get; set; }
        public string FIO { get; set; }
        public string NumberPhone { get; set; }
        public string Email { get; set; }
        public Nullable<System.DateTime> BirthDate { get; set; }
        public Nullable<int> IdGender { get; set; }
    
        public virtual Gender Gender { get; set; }
        public virtual ICollection<ReaderTicket> ReaderTicket { get; set; }
    }
}
