//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lib2122.DbConnection
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReaderTicket
    {
        public ReaderTicket()
        {
            this.HistoryReaderTicket = new HashSet<HistoryReaderTicket>();
        }
    
        public int Id { get; set; }
        public Nullable<int> IdReader { get; set; }
        public Nullable<System.DateTime> DateRegistr { get; set; }
        public Nullable<System.DateTime> DateEnd { get; set; }
    
        public virtual ICollection<HistoryReaderTicket> HistoryReaderTicket { get; set; }
        public virtual Reader Reader { get; set; }
    }
}
